import { ImArrowDownLeft, ImArrowDownRight } from "react-icons/im";

export const drivers = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    birthday: "19/06/1990",
    state: "California",
    homeLocation: "San Francisco",
    workLocation: "Mountain View",
    otherDetails: {
      orderAccept: 10,
      orderCancel: 2,
      orderSkipped: 1,
      rate: 4.5,
      cash: 1000,
    },
    value: "High",
    comment: "Lorem ipsum dolor sit amet",
    arrow: <ImArrowDownRight />,
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    birthday: "20/07/1991",
    state: "New York",
    homeLocation: "Brooklyn",
    workLocation: "Manhattan",
    otherDetails: {
      orderAccept: 15,
      orderCancel: 3,
      orderSkipped: 2,
      rate: 4.7,
      cash: 1500,
    },
    value: "Medium",
    comment: "Sed do eiusmod tempor incididunt",
    arrow: <ImArrowDownLeft />,
  },
  {
    id: 3,
    firstName: "Bob",
    lastName: "Johnson",
    birthday: "21/08/1992",
    state: "Texas",
    homeLocation: "Austin",
    workLocation: "Dallas",
    otherDetails: {
      orderAccept: 12,
      orderCancel: 1,
      orderSkipped: 0,
      rate: 4.8,
      cash: 1200,
    },
    value: "Low",
    comment: "Ut enim ad minim veniam",
    arrow: <ImArrowDownRight />,
  },
  {
    id: 4,
    firstName: "Alice",
    lastName: "Williams",
    birthday: "22/09/1993",
    state: "Florida",
    homeLocation: "Orlando",
    workLocation: "Miami",
    otherDetails: {
      orderAccept: 14,
      orderCancel: 2,
      orderSkipped: 1,
      rate: 4.6,
      cash: 1300,
    },
    value: "High",
    comment: "Duis aute irure dolor in reprehenderit",
    arrow: <ImArrowDownLeft />,
  },
  {
    id: 5,
    firstName: "Charlie",
    lastName: "Brown",
    birthday: "23/10/1994",
    state: "Illinois",
    homeLocation: "Chicago",
    workLocation: "Springfield",
    otherDetails: {
      orderAccept: 16,
      orderCancel: 3,
      orderSkipped: 2,
      rate: 4.9,
      cash: 1400,
    },
    value: "Medium",
    comment: "Excepteur sint occaecat cupidatat non proident",
    arrow: <ImArrowDownRight />,
  },
  {
    id: 6,
    firstName: "David",
    lastName: "Davis",
    birthday: "24/11/1995",
    state: "Washington",
    homeLocation: "Seattle",
    workLocation: "Spokane",
    otherDetails: {
      orderAccept: 18,
      orderCancel: 4,
      orderSkipped: 3,
      rate: 4.4,
      cash: 1500,
    },
    value: "Low",
    comment: "Nisi ut aliquid ex ea commodi consequatur",
    arrow: <ImArrowDownLeft />,
  },
  {
    id: 7,
    firstName: "Eva",
    lastName: "Miller",
    birthday: "25/12/1996",
    state: "Oregon",
    homeLocation: "Portland",
    workLocation: "Salem",
    otherDetails: {
      orderAccept: 20,
      orderCancel: 5,
      orderSkipped: 4,
      rate: 4.3,
      cash: 1600,
    },
    value: "High",
    comment: "Quis autem vel eum iure reprehenderit qui",
    arrow: <ImArrowDownRight />,
  },
];
